name: Deploy pages
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Handle Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Check node version
        run: node -v

      - name: Check yarn version
        run: yarn -v

      - name: Install dependecies
        run: yarn install

      - name: Check Build
        env:
          REACT_APP_ENKETO: http://localhost:8065
          REACT_APP_GET_FORM: http://localhost:8080
          REACT_APP_ENKETO_ITI_FLOW: http://localhost:8066
          REACT_APP_GET_FORM_ITI_FLOW: http://localhost:3002
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
